// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelesEducacao.Alunos.Data;

#nullable disable

namespace TelesEducacao.Alunos.Data.Migrations
{
    [DbContext(typeof(AlunosContext))]
    [Migration("20260218221527_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.AulaConluida", b =>
                {
                    b.Property<Guid>("AulaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.HasKey("AulaId", "MatriculaId");

                    b.HasIndex("MatriculaId");

                    b.ToTable("AulasConcluidas");
                });

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlunoId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatriculaStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("AlunoId1");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.AulaConluida", b =>
                {
                    b.HasOne("TelesEducacao.Alunos.Domain.Matricula", "Matricula")
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.Certificado", b =>
                {
                    b.HasOne("TelesEducacao.Alunos.Domain.Matricula", "Matricula")
                        .WithMany("Certificados")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.Matricula", b =>
                {
                    b.HasOne("TelesEducacao.Alunos.Domain.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelesEducacao.Alunos.Domain.Aluno", null)
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId1");

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("TelesEducacao.Alunos.Domain.Matricula", b =>
                {
                    b.Navigation("Certificados");
                });
#pragma warning restore 612, 618
        }
    }
}
